import Head from "next/head";
import styled from "styled-components";
import HomePage from "./home";

export const OutLayer = styled.div`
  z-index: 1;
  background: rgba(255, 255, 255, 0.2);
  transform: rotate(-4deg);
  border-radius: 40px;
  height: 90vh;
  width: 92vw;
  @media (max-height: 850px) {
    height: 850px;
  }
`;

export const Foundation = styled.div`
  background: rgba(255, 255, 255, 0.5);
  box-shadow: 0px 5px 7px 0px rgba(255, 255, 255, 0.5);
  border-radius: 40px;
  border: 3px solid #ffffff;
  transform: rotate(4deg);
  width: 92vw;
  height: 100%;
  z-index: 10;
  display: flex;
  @media (max-height: 850px) {
    height: 850px;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Exchange</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage />
    </>
  );
}
